name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:
    name: Backend - Test (pytest)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        env:
          # Minimal env so pydantic Settings() validation passes during import
          DATABASE_URL: sqlite:///./test.db
          REDIS_URL: redis://localhost:6379
          JWT_SECRET_KEY: test-secret-key
          JWT_ALGORITHM: HS256
          JWT_EXPIRE_MINUTES: '30'
          APP_NAME: RAG Console
          APP_VERSION: 1.0.0
          DEBUG: 'false'
        run: |
          pytest -q

  frontend:
    name: Frontend - Build (Vite/React)
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: front
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: front/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Build
        env:
          # Point to local backend in CI if needed by build; adjust as necessary
          VITE_API_BASE_URL: http://localhost:8000/api/v1
        run: npm run build
